BitMascot/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BitMascot.Models
{
    public class LoginModel
    {
    }
}

BitMascot/Models/UserModel.cs
using BitMascot.Enum;
using BitMascot.HelperCodes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BitMascot.Models
{
    public class UserModel
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public DateTime DOB { get; set; }
        public string Password { get; set; }
        public UserType UserType { get; set; }
        public bool RememberMe { get; set; }
        public string NewPassword { get; set; }

        DataAccess.DataAccess DA;

        public AnyStatus RegisterUser()
        {
            UserModel NewUser = new UserModel()
            {
                FirstName = this.FirstName,
                LastName = this.LastName,
                Address = this.Address,
                PhoneNo = this.PhoneNo,
                Email = this.Email,
                DOB = this.DOB,
                Password = PasswordHashing.HashPassword(this.Password),
                UserType = UserType.User
            };

            DA = new DataAccess.DataAccess();
            return (AnyStatus)DA.AddNewUser(NewUser);
        }

        public UserModel UserLogin()
        {
            DA = new DataAccess.DataAccess();
            return DA.GetUserByEmail(this.Email);
        }

        public AnyStatus ChangePassword()
        {
            DA = new DataAccess.DataAccess();
            UserModel UserByID = DA.GetUserByID(this.UserID);

            if (PasswordHashing.VerifyPassWord(this.Password, UserByID.Password))
            {
                return (AnyStatus)DA.ChangeUserPassword(this.UserID, PasswordHashing.HashPassword(this.NewPassword));
            }
            else
            {
                return AnyStatus.Failed;
            }
        }

        public UserModel GetUserByID(int UserID)
        {
            DA = new DataAccess.DataAccess();
            return DA.GetUserByID(UserID);
        }

        public List<UserModel> GetUserList()
        {
            DA = new DataAccess.DataAccess();
            return DA.GetUserList();
        }

    }
}

BitMascot/Controllers/AnonymousController.cs
using BitMascot.Enum;
using BitMascot.HelperCodes;
using BitMascot.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BitMascot.Controllers
{
    public class AnonymousController : Controller
    {
        // GET: Anonymous
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        public JsonResult RegisterNewUser(UserModel NewUser)
        {
            object data = null;

            data = NewUser.RegisterUser();

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UserLogin(UserModel LoginInfo)
        {
            object data = null;

            //data = NewUser.RegisterUser();
            UserModel UserByEmail = LoginInfo.UserLogin();

            if (UserByEmail != null)
            {
                if (PasswordHashing.VerifyPassWord(LoginInfo.Password, UserByEmail.Password))
                {
                    Session["UserModel"] = UserByEmail;
                    FormsAuthentication.SetAuthCookie(UserByEmail.Email, LoginInfo.RememberMe);

                    data = AnyStatus.Successful;
                }
                else
                {
                    data = AnyStatus.Failed;
                }
            }
            else
            {
                data = AnyStatus.Failed;
            }

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session["UserModel"] = null;
            return RedirectToAction("Login");
        }

    }
}

BitMascot/Controllers/HomeController.cs
using BitMascot.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BitMascot.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        public JsonResult ChangeUserPassword(UserModel ChangeUserPassword)
        {
            object data = null;
            
            data = ChangeUserPassword.ChangePassword();

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UserProfile()
        {
            return View();
        }

        public JsonResult GetUserByID(int UserID)
        {
            object data = null;

            UserModel UserInfo = new UserModel();
            data = UserInfo.GetUserByID(UserID);

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UserList()
        {
            return View();
        }

        public JsonResult GetUserList()
        {
            object data = null;

            UserModel UserInfo = new UserModel();
            data = UserInfo.GetUserList();

            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

BitMascot/Views/Anonymous/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>BitMascot | Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/iCheck/square/blue.css" rel="stylesheet" />

</head>
<body class="hold-transition login-page" style="background-color:#112038;">
    <div class="login-box">
        <div class="login-logo">
            @*<a href="../../index2.html"><b>Admin</b>LTE</a>*@
            <img src="~/Images/company-logo.png" />
        </div><!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Login Panel</p>

            <div class="form-group has-feedback">
                <input type="email" class="form-control" placeholder="Email" id="txtEmail">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="Password" id="txtPassword">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox" id="chkRememberMe"> Remember Me
                        </label>
                    </div>
                </div><!-- /.col -->
                <div class="col-xs-4">
                    <button type="" class="btn btn-primary btn-block btn-flat" id="btnSignIn">Sign In</button>
                </div><!-- /.col -->
            </div>

            @*<div class="social-auth-links text-center">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
                    <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
                </div>*@

            @*<a href="#">I forgot my password</a><br>*@
            <a href="@Url.Action("Register","Anonymous")" class="text-center">Register</a>

        </div>
    </div>
</body>
</html>


<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/iCheck/icheck.min.js"></script>

<script src="~/Scripts/sweet-alert.js"></script>
<link href="~/Content/sweet-alert.css" rel="stylesheet" />

<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>

<script>

    $(document).ready(function () {

        $('#btnSignIn').click(function () {

            var loginInfo = {
                "Email": $('#txtEmail').val(),
                "Password": $('#txtPassword').val(),
                "RememberMe": $('#chkRememberMe').is(':checked')
            };

            var controllerUrl = '@Url.Action("UserLogin", "Anonymous")';
            $.ajax({
                url: controllerUrl
                , data: JSON.stringify({ LoginInfo: loginInfo })
                , dataType: "json"
                , type: 'POST'
                , contentType: 'application/json; charset=utf-8'
                , success: function (data) {
                    if (data == 1) {
                        window.location.href = "@Url.Action("Index","Home")";
                    }
                    else {
                        swal('Invalid email address.', '', 'error');
                    }
                }
                , error: function (data) {
                    swal('Invalid Email or Password', '', 'error');
                }
            });

        });

    });

</script>

@**@

BitMascot/Views/Anonymous/Register.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BitMascot | Register</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/iCheck/square/blue.css" rel="stylesheet" />
</head>
<body class="hold-transition register-page" style="background-color:#112038;">
    <div class="register-box">
        <div class="register-logo">
            <img src="~/Images/company-logo.png" />
        </div>

        <div class="register-box-body">
            <p class="login-box-msg">Registration Panel</p>

            <form id="frmRegister" method=""></form>

            @*First Name*@
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="First Name" name="FirstName" id="txtFirstName">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>

            @*Last Name*@
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="Last Name" name="LastName" id="txtLastName">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>

            @*Address*@
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="Address" name="Address" id="txtAddress">
                <span class="glyphicon glyphicon-map-marker form-control-feedback"></span>
            </div>

            @*Phone*@
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="Phone" name="Phone" id="txtPhone">
                <span class="glyphicon glyphicon-phone form-control-feedback"></span>
            </div>

            @*Email*@
            <div class="form-group has-feedback">
                <input type="email" class="form-control" placeholder="Email" name="Email" id="txtEmail">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>

            @*DOB*@
            <div class="form-group has-feedback">
                <input type="text" class="form-control datepicker" placeholder="DOB" name="DOB" id="txtDOB">
                <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
            </div>

            @*Password*@
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="Password" name="Password" id="txtPassword">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>

            <div class="row">
                <div class="col-xs-8">
                    <p>- OR - <br />Just <a href="@Url.Action("Login","Anonymous")" class="text-center">Login</a> instead.</p>
                </div>
                <div class="col-xs-4">
                    <button class="btn btn-primary btn-block btn-flat" id="btnRegister">Register</button>
                </div><!-- /.col -->
            </div>

            @*<div class="social-auth-links text-center">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using Facebook</a>
                    <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign up using Google+</a>
                </div>*@



        </div>
    </div>

</body>
</html>

<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/iCheck/icheck.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<link href="~/Content/datepicker/datepicker3.css" rel="stylesheet" />
<script src="~/Scripts/datepicker/bootstrap-datepicker.js"></script>

<script src="~/Scripts/sweet-alert.js"></script>
<link href="~/Content/sweet-alert.css" rel="stylesheet" />

<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });

        //Date picker
        $('.datepicker').datepicker({
            //Closes after date is picked
            autoclose: true
            //, format: 'dd/mm/yy'
        });
        //Setting today's date as default date
        $('.datepicker').datepicker('setDate', 'now');

        //$("#frmRegister").validate({
        //    rules: {
        //        FirstName: "required",
        //        LastName: "required",
        //        Password: {
        //            required: true,
        //            minlength: 5
        //        },
        //        Email: {
        //            required: true,
        //            email: true
        //        },
        //        Phone: {
        //            required: true
        //        },
        //        Address: {
        //            required: true
        //        },
        //        DOB: {
        //            required: true
        //        }
        //    },
        //    messages: {
        //        FirstName: "Please enter your firstname",
        //        LastName: "Please enter your firstname",
        //        //password: {
        //        //    required: "Please provide a password",
        //        //    minlength: "Your password must be at least 5 characters long"
        //        //},
        //        Password: "Please enter a strong password",
        //        Email: "Please enter a valid email address",
        //        Phone: "Please your phone number",
        //        Address: "Please your address",
        //        DOB: "Please select your Date of Birth"

        //    }
        //});
    });
</script>

<script>

    $(document).ready(function () {

        $('#btnRegister').click(function () {

            if ($('#txtEmail').val() == '' || $('#txtPassword').val() == '') {
                swal('Email & Password is required !!', 'Stop', 'warning');
                return;
            }

            var user = {
                "FirstName":$('#txtFirstName').val(),
                "LastName":$('#txtLastName').val(),
                "Address":$('#txtAddress').val(),
                "PhoneNo":$('#txtPhone').val(),
                "Email":$('#txtEmail').val(),
                "DOB":$('#txtDOB').val(),
                "Password": $('#txtPassword').val()
            };
            
            var controllerUrl = '@Url.Action("RegisterNewUser", "Anonymous")';
            $.ajax({
                url: controllerUrl
                , data: JSON.stringify({ NewUser: user })
                , dataType: "json"
                , type: 'POST'
                , contentType: 'application/json; charset=utf-8'
                , success: function (data) {
                    if (data == 1) {
                        swal('Successful registration.', "Please log in to the system", "success");
                        window.location.href = "@Url.Action("Login","Anonymous")";
                    }
                    else if (data == 2) {
                        swal('Email address already exists !!', '', 'warning');
                    }
                    else {
                        swal('Error while saving data.', '','');
                    }
                }
                , error: function (data) {
                    swal(data);
                }
            });

        });

    });

</script>

BitMascot/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BitMascot/Views/Home/ChangePassword.cshtml
@using BitMascot.Models
@{
    ViewBag.Title = "Change Password";
}

@{ 
    var SessionUser = (UserModel)Session["UserModel"];
}

<section class="content">

    <h1 align="center" class="navy text-bold" style="font-family:Calibri;"><b>Change Password</b></h1>

    <div class="row">

        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">

                    <div class="form-horizontal">

                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="col-sm-1"></div>
                                <label class="col-sm-2">Current Password</label>
                                <div class="col-sm-6">
                                    <input class="form-control" type="password" placeholder="Current Password" id="txtCurrentPassword">
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                        </div>

                    </div>

                    <div class="form-horizontal">

                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="col-sm-1"></div>
                                <label class="col-sm-2">New Password</label>
                                <div class="col-sm-6">
                                    <input class="form-control" type="password" placeholder="New Password" id="txtNewPassword">
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                        </div>

                    </div>

                    <div class="form-horizontal">

                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="col-sm-1"></div>
                                <label class="col-sm-2">Confirm Password</label>
                                <div class="col-sm-6">
                                    <input class="form-control" type="password" placeholder="Confirm Password" id="txtConfirmPassword">
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                        </div>

                    </div>

                    <div class="form-horizontal">

                        <div class="col-lg-12">
                            <div class="form-group">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-6">
                                    <button class="btn btn-success" id="txtResetPassword">Reset Pasword</button>
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                        </div>

                    </div>

                </div>
                <!-- /.box-body -->
                <!-- /.box -->
            </div>
        </div>

    </div>

</section>

<script src="~/Scripts/jquery.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        $('#txtResetPassword').click(function(){

            var currentPass = $('#txtCurrentPassword').val();
            var newPass = $('#txtNewPassword').val();
            var confirmPass = $('#txtConfirmPassword').val();

            if (newPass !== confirmPass) {
                swal('New & Confirm Password do not match.', '', 'error');
                return;
            }

            var UserPassInfo = {
                "UserID" : @SessionUser.UserID,
                "Password": currentPass,
                "NewPassword" : newPass
            };

            var controllerUrl = '@Url.Action("ChangeUserPassword", "Home")';
            $.ajax({
                url: controllerUrl
                , data: JSON.stringify({ ChangeUserPassword : UserPassInfo })
                , dataType: "json"
                , type: 'POST'
                , contentType: 'application/json; charset=utf-8'
                , success: function (data) {
                    if (data == 1) {
                        window.location.href = "@Url.Action("Logout", "Anonymous")";
                    }
                    else {
                        swal('Unable to Login', '', 'error');
                    }
                }
                , error: function (data) {
                    console.log(data);
                }
            });

        });

    });

</script>

BitMascot/Views/Shared/_Layout.cshtml
@using BitMascot.Enum
@using BitMascot.Models
@{
    var UserSesion = (UserModel)Session["UserModel"];
    if (UserSesion == null)
    {
        Url.Action("Login", "Anonymous");
        new RedirectToRouteResult(new RouteValueDictionary { { "action", "Login" }, { "controller", "Anonymous" } });
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BitMascot | @ViewBag.Title</title>


    @*****************************LOADED CSS***********************************@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/_all-skins.css" rel="stylesheet" />
    <link href="~/Content/iCheck/all.css" rel="stylesheet" />
    <link href="~/Content/morris.css" rel="stylesheet" />
    <link href="~/Content/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" />
    <link href="~/Content/datepicker/datepicker3.css" rel="stylesheet" />
    <link href="~/Content/daterangepicker/daterangepicker.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" />
    <link href="~/Content/select2/select2.min.css" rel="stylesheet" />

    @*FOR DATATABLE*@
    @*<link href="~/Content/datatables/jquery.dataTables.min.css" rel="stylesheet" />*@
    <link href="~/Content/datatables/dataTables.bootstrap.css" rel="stylesheet" />

    @*SweetAlert*@
    <link href="~/Content/sweet-alert.css" rel="stylesheet" />
    @*<link href="~/Content/sweetalert.css" rel="stylesheet" />*@

    @*Custom Layout*@
    <link href="~/Content/CustomCss/customUiDesign.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    @*****************************LOADED CSS***********************************@

</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">

            <nav class="navbar navbar-static-top">

                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">

                        <li class="dropdown profile-username">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @UserSesion.FirstName&nbsp;@UserSesion.LastName
                                <i class="fa fa-angle-down" style="font-size:large;"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="footer"><a href="@Url.Action("Logout", "Anonymous")">Logout</a></li>
                            </ul>

                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <aside class="main-sidebar">

            <section class="sidebar">
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>

                    @if (UserSesion.UserType == UserType.User)
                    {
                        <li><a href="@Url.Action("UserProfile", "Home")"><i class="fa fa-circle-o text-aqua"></i> <span>Profile</span></a></li>
                        <li><a href="@Url.Action("ChangePassword", "Home")"><i class="fa fa-circle-o text-aqua"></i> <span>Change Password</span></a></li>
                    }

                    @if (UserSesion.UserType == UserType.Admin)
                    {
                        <li><a href="@Url.Action("UserList", "Home")"><i class="fa fa-circle-o text-aqua"></i> <span>User List</span></a></li>
                    }

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <div class="content-wrapper">

            @RenderBody()
        </div>

    </div>
</body>

</html>

@*****************************LOADED SCRIPTS***********************************@

<script>
    var AdminLTEOptions = {
        //Enable sidebar expand on hover effect for sidebar mini
        //This option is forced to true if both the fixed layout and sidebar mini
        //are used together
        //sidebarExpandOnHover: true,
        //BoxRefresh Plugin
        //enableBoxRefresh: true,
        //Bootstrap.js tooltip
        enableBSToppltip: true
    };
</script>

<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/jQueryUI/jquery-ui.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/raphael-min.js"></script>
<script src="~/Scripts/morris/morris.min.js"></script>
<script src="~/Scripts/sparkline/jquery.sparkline.min.js"></script>
<script src="~/Scripts/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="~/Scripts/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="~/Scripts/knob/jquery.knob.js"></script>
<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/daterangepicker/daterangepicker.js"></script>
<script src="~/Scripts/datepicker/bootstrap-datepicker.js"></script>
<script src="~/Scripts/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script src="~/Scripts/slimScroll/jquery.slimscroll.min.js"></script>
<script src="~/Scripts/fastclick/fastclick.min.js"></script>
<script src="~/Scripts/app.min.js"></script>
<script src="~/Scripts/dashboard.js"></script>
<script src="~/Scripts/demo.js"></script>
<script src="~/Scripts/select2/select2.full.min.js"></script>
<script src="~/Scripts/input-mask/jquery.inputmask.js"></script>
<script src="~/Scripts/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="~/Scripts/input-mask/jquery.inputmask.extensions.js"></script>
<script src="~/Scripts/iCheck/icheck.min.js"></script>

@*FOR DATATABLE*@
<script src="~/Scripts/datatables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/datatables/dataTables.bootstrap.min.js"></script>

@*SweetAlert*@
<script src="~/Scripts/sweet-alert.js"></script>
@*<script src="~/Scripts/sweetalert.js"></script>*@


@* Pace *@
<script src="~/Scripts/pace/pace.min.js"></script>


@*****************************LOADED SCRIPTS***********************************@

@*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@